workflows:
  ios-release:
    name: Unity iOS Release

    instance_type: mac_mini_m2

    environment:
      xcode: latest

    ios_signing:
      distribution_type: app_store
      bundle_identifier: com.magicalorbs.test

    scripts:
      - name: Configure code signing
        script: |
          xcode-project use-profiles

      - name: Archive
        script: |
          xcodebuild \
            -project Unity-iPhone.xcodeproj \
            -scheme Unity-iPhone \
            -configuration Release \
            -archivePath build/App.xcarchive \
            archive

    artifacts:
      - build/App.xcarchive